# Generated by Django 5.2 on 2025-04-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontodeacesso',
            old_name='ativo',
            new_name='status',
        ),
    ]
