# Generated by Django 5.2 on 2025-05-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_equipe_ordemdeservico_paginaacesso_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.CharField(choices=[('10', '10 megas'), ('10F', '10 Megas Fibre'), ('100', '100 Megas'), ('100F', '100 Megas Fibra'), ('500', '500 Megas'), ('500F', '500 Megas Fibra')], default=10, max_length=4),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('10', '10 megas'), ('10F', '10 Megas Fibre'), ('100', '100 Megas'), ('100F', '100 Megas Fibra'), ('500', '500 Megas'), ('500F', '500 Megas Fibra')], default=10, max_length=4),
        ),
    ]
