# Generated by Django 5.2 on 2025-05-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_cliente_email_cliente_endereco_cliente_plano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='status',
        ),
        migrations.AddField(
            model_name='cliente',
            name='devendo',
            field=models.BooleanField(default=False),
        ),
    ]
