# Generated by Django 5.2 on 2025-05-13 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_remove_cliente_status_cliente_devendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.equipe'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prazo',
            field=models.DateTimeField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(choices=[('R', 'Realizada'), ('E', 'Em andamento'), ('D', 'Designada'), ('S', 'Especificada')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'media'), ('A', 'alta'), ('S', 'super alta')], default='B', max_length=4),
        ),
    ]
