# Generated by Django 5.2 on 2025-05-13 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_ordemdeservico_descricao_ordemdeservico_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
