# Generated by Django 5.2 on 2025-05-13 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_alter_ordemdeservico_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
