# Generated by Django 5.2 on 2025-05-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_alter_ordemdeservico_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='conta_bancaria',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
